settings:
  title: 'DolaNetworks Status Page'
  url: 'https://status.1ab.cc' # used for Slack messages
  logo: dolacmeo_256.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服务均在线'
  notAllmonitorsOperational: '部分服务异常'
  monitorLabelOperational: '在线'
  monitorLabelNotOperational: '异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '均正常'
  dayInHistogramNotOperational: ' 异常(s)' # xx incident(s) recorded

monitors:
  - id: website-profile-page
    name: 'dolacmeo profile page'
    description: 'by bento.me' # default=empty
    url: 'https://dolacmeo.1ab.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: website-blog
    name: 'dolacmeo blog'
    description: 'by NotionNext' # default=empty
    url: 'https://blog.1ab.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: website-allfree
    name: 'free share page'
    description: 'by super.so' # default=empty
    url: 'https://allfree.super.site/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: domains-1ab.cc
    name: 'Domain: 1ab.cc'
    description: 'by Synology Web Station' # default=empty
    url: 'https://1ab.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: domains-1234566.xyz
    name: 'Domain: 1234566.xyz'
    description: 'by cloudflare page' # default=empty
    url: 'https://1234566.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: domains-268435455.xyz
    name: 'Domain: 268435455.xyz'
    description: 'by cloudflare page' # default=empty
    url: 'https://268435455.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: domains-1abcd.eu.org
    name: 'Domain: 1abcd.eu.org'
    description: 'by cloudflare page' # default=empty
    url: 'https://1abcd.eu.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: domains-dolacmeo.eu.org
    name: 'Domain: dolacmeo.eu.org'
    description: 'by cloudflare page' # default=empty
    url: 'https://dolacmeo.eu.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
