settings:
  title: 'DolaNetworks Status Page'
  url: 'https://status.1ab.cc' # used for Slack messages
  logo: dolacmeo_256.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服务均在线All Systems Operational'
  notAllmonitorsOperational: '部分服务异常Not All Systems Operational'
  monitorLabelOperational: '在线Operational'
  monitorLabelNotOperational: '异常Not Operational'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据No data'
  dayInHistogramOperational: '均正常All good'
  dayInHistogramNotOperational: ' 异常(s)' # xx incident(s) recorded

monitors:
  - id: dolanas-default-page # unique identifier
    name: 'DolaNAS default page.'
    description: 'from DolaNetwork.' # default=empty
    url: 'https://1ab.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
